# Generated by Django 4.1.3 on 2022-11-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Typeofloading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofloading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Typeofunloading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofunloading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=200)),
                ('date_of_transportation', models.DateField()),
                ('price', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.cargo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.currency')),
                ('customers_contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.person')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.itinerary')),
                ('taxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.tax')),
                ('typesofloading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.typeofloading')),
                ('typesofunloading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.typeofunloading')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.volume')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.weight')),
            ],
        ),
    ]
