# Generated by Django 4.1.3 on 2022-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('itinerary', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('firm', models.CharField(max_length=255)),
                ('customers_contact_person', models.CharField(max_length=255)),
                ('auto', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
    ]
