# Generated by Django 4.1.3 on 2022-12-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='title',
        ),
    ]
