# Generated by Django 4.1.3 on 2022-12-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0003_remove_carrier_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.itinerary'),
        ),
    ]
