# Generated by Django 4.1.3 on 2022-12-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0004_alter_carrier_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary1', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='title',
            new_name='itinerary',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.itinerary1'),
        ),
    ]
