# Generated by Django 4.1.3 on 2022-12-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0005_itinerary1_rename_title2_actual_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary1',
            old_name='itinerary1',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='itinerary',
            field=models.CharField(max_length=255),
        ),
    ]
