# Generated by Django 4.1.3 on 2022-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0006_rename_itinerary1_itinerary1_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
