# Generated by Django 4.1.3 on 2022-12-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0007_alter_carrier_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itinerary1',
        ),
    ]
