# Generated by Django 4.1.3 on 2022-12-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0009_carrier_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='author',
        ),
    ]
